### ISSUE TITLE
More comments

### ISSUE THREAD

**Issue by sauljaffe** [HarmlessHarm/HarmlessKey#35]
Still playing with the software and trying to figure things out:

- When I reset an encounter, the system resets everything including inactive monsters, their health, initiative, etc.  It DOES NOT reset the health of the players to what it was before the encounter started (which may not be their full health so using the "reset player health" doesn't help)

- There doesn't seem to be any way to set reminders prior to starting the encounter.  That means that I have to take time during the gaming session to set that up.  I should be able to set reminders beforehand (like at home before the gaming session starts) so when the encounter starts, everything is ready to go.

- There doesn't seem to be any way to handle "special attacks".  For example, an upcoming battle is against stirges.  The stirges, once they hit, don't attack again but instead drain blood.  There's no way to track how much blood each stirge has drained.

- I have a laptop and a tablet.  I'd like to set up one as a "master" so that it shows all the things that I, as a DM, want and need to see while the other is set up as a "display" that shows only what I want the characters/players to see.  I can't figure out how to do this, or whether or not it's possible.  The documentation suggests that it is possible but I can't figure it out.

_Edit: fixed layout to improve readability._

**Comment by HarmlessHarm** [comment]
Hi Sauljaffe,

Thanks for the new feedback.

1. Resetting the encounter does not reset the players' health no. This feature was never meant as an encounter undo button, we do not expect that people would ever want to undo an entire encounter. Especially not one that has already been finished. Adding this is also not something that is easily done as there are too many ways that a player can lose health between finishing an encounter and resetting it.

2. Custom reminders which can be saved is something that is on our list. We've actually asked our patrons which feature they would prefer: a better loot system or custom reminders. The majority voted loot system so that is currently first on our list. In time custom reminders will be added.

3. In your previous issue, I already addressed abilities like this. This specific special ability can easily be done by just attacking and clicking hit when the Strige is attached to a target. You can write on a piece of paper how much damage has been done this way. Our app will never beat the flexibility of pen and paper.

4. This is actually something that is possible yes! It's one of our coolest features if we say so ourselves. In the top-right of your screen, next to your profile image, you'll see an icon of a link. When you click it, a link and a QR code are shown which you can use to go to the _player window_. In this window, players, or you yourself on a different device, can select the campaign. When you then press the _live_ button in one of the campaigns in your DM overview, your player window will show the initiative tracker.

We hope we've hereby informed you sufficiently.

Harm & Key

**Comment by sauljaffe** [comment]
> On Dec 3, 2019, at 6:28 PM, Harm Manders <notifications@github.com> wrote:
> 
> Hi Sauljaffe,
> 
> Thanks for the new feedback.
> 
> 	• Resetting the encounter does not reset the players' health no. This feature was never meant as an encounter undo button, we do not expect that people would ever want to undo an entire encounter.

Then you may not have played with the same groups I have… where people decide that there’s been a massive screw-up somewhere and want to roll back the entire encounter and start again.

And what was the reset button meant for if not to reset the encounter back to the state it was in before running it?

> Especially not one that has already been finished. Adding this is also not something that is easily done
 
You take a snapshot of the state of everything at the start and then put it back when someone does a reset.  This is the whole methodology behind some areas of computers such as database management.

> as there are too many ways that a player can lose health between finishing an encounter and resetting it.

I can’t think of one.

> 	• This is actually something that is possible yes! It's one of our coolest features if we say so ourselves. In the top-right of your screen, next to your profile image, you'll see an icon of a link. When you click it, a link and a QR code are shown which you can use to go to the player window. In this window, players, or you yourself on a different device, can select the campaign. When you then press the live button in one of the campaigns in your DM overview, your player window will show the initiative tracker.

I tried this and it didn’t work. 

When it recognized the QR code, I got a message asking me if I want to open Hamrless Key in Safari.  I clicked on that and I went to harmless key in Safari… and just say a mostly blank screen.  There was the header at the top… but the rest of the screen was blank.  Clicking the “live” button didn’t change anything, and even clicking through a few turns made no difference - the screen stayed mostly blank.

If it helps, the “main” window was in Chrome on a MacBook Pro and the other device was an iPad 7.


--
Saul Jaffe
sauljaffe@newsguy.com

“Together, we must remove the physical barriers we have created and the social barriers that we have accepted. For ours will never be a truly prosperous nation until all within it prosper.”

President George Bush
upon signing the Americans with Disabilities Act
July 26, 1990

**Comment by HarmlessHarm** [comment]
Hi Saul,

> Then you may not have played with the same groups I have… where people decide that there’s been a massive screw-up somewhere and want to roll back the entire encounter and start again. And what was the reset button meant for if not to reset the encounter back to the state it was in before running it?

Wow, rolling back an entire encounter was not something we had anticipated. The reset option was meant to reuse an encounter somewhere else in your campaign. (I have one called random forest encounter with some typical forest foes, I set the NPCs that I don't want to use this time on inactive)
We've recently added the "unfinish" button next to the reset button that restores the encounter to the state it had before it was finished. If your combat log is still available you can then undo some of the actions that were taken. Hopefully that can help already for some of your problems.

> > Especially not one that has already been finished. Adding this is also not something that is easily done

> You take a snapshot of the state of everything at the start and then put it back when someone does a reset.  This is the whole methodology behind some areas of computers such as database management.

> > as there are too many ways that a player can lose health between finishing an encounter and resetting it.

> I can’t think of one.

I thought of taking a snapshot from before the encounter and save that. But if your party has already started encounter 2 after finishing encounter 1, and you then decide to reset encounter 1, you party will also recover all the health lost in encounter 2. This would mean that you can only reset before you'd start another encounter. It would also mean that the original use of the reset button would not be available.
It could be that some day this feature could make it to the app, but we are of the opinion that with the added "unfinish" button, we give the ability to undo the encounter.

> When it recognized the QR code, I got a message asking me if I want to open Hamrless Key in Safari.  I clicked on that and I went to harmless key in Safari… and just say a mostly blank screen.  There was the header at the top… but the rest of the screen was blank.  Clicking the “live” button didn’t change anything, and even clicking through a few turns made no difference - the screen stayed mostly blank.

It sounds like you don't have your campaign set to public. I know it sounds counter intuitive as you are logged into your own account and can't see your private campaigns. We currently don't check for the current logged in user in the player window. This is something we'll add to our list.
For now it's fixed by setting the campaign you want to show on your second device to public. It will then show up. By the way, public campaigns can only be viewed by other people if they have the exact link to your page, they can't find it anywhere without you sending it to them.

All the best,

Harm & Key

**Comment by sauljaffe** [comment]
> On Dec 4, 2019, at 7:02 AM, Harm Manders <notifications@github.com> wrote:
> 
> Hi Saul,
> 
> We've recently added the "unfinish" button next to the reset button that restores the encounter to the state it had before it was finished. If your combat log is still available you can then undo some of the actions that were taken. Hopefully that can help already for some of your problems.

I’ll give it a try and my next session and see if that works.

> It sounds like you don't have your campaign set to public. I know it sounds counter intuitive as you are logged into your own account and can't see your private campaigns. We currently don't check for the current logged in user in the player window. This is something we'll add to our list.
> For now it's fixed by setting the campaign you want to show on your second device to public. It will then show up. By the way, public campaigns can only be viewed by other people if they have the exact link to your page, they can't find it anywhere without you sending it to them.

Ok, first of all, I didn’t know there was a private/public campaign setting.  I had to look for it once you told me it was there.

Secondly, this is not *quite* the behavior I want or expect.  When I’m on the laptop, I start an encounter… I have to also start the encounter that’s being mirrored on the iPad.  Also, what appears on the iPad is *everything*.  I don’t want it to be everything - only those things that I want it to show.

Unless I’m mistaken, it looks like to do what I want I need to create another player character and log in as that player character on the iPad to see what player characters should see.  That seems like an extra unnecessary step to me.

Essentially, I was thinking of something more like what Roll20 does where the DM can set the window to either “DM mode” or “Player Mode” - and so you can have one screen set to “Player Mode" and the other to “DM mode” and it behaves like i would expect it to with the “Player Mode” device only displaying those things in player mode.  On Roll20, Fantasy Ground, etc. I don’t need to do that extra step of creating a dummy player character and logging in as the player character - I just have to set the second screen to “Player Mode” once and then the rest of the night, it shows what I want it to show.

I’m not sure if that’s making sense but if you’ve used Roll20 or another online D&D tool similar to it, and used a secondary display, you’ll understand what I mean…

BTW, the reason to use Harmless Key rather than Roll20 is that (a) Roll20 costs a lot more and (b) it is so much more than an encounter management tool and really bogs things down with the graphics and moving players around on maps, etc.  It’s far more than I want and, as I said, costs a lot more.

The reason I want to use a display screen for the players in Harmless Key is so that they can see whose turn it is, who they are targeting, conditions, reminders, etc. and, if I allow it for that encounter, the HP of the monsters they are fighting.  We’d still be using the tabletop and miniatures for the battle, and they’d still be rolling their own dice, but this way they would have some visual idea of what the status of the fight is as it goes on and can catch errors I might make.

--
Saul Jaffe
sauljaffe@newsguy.com

“Together, we must remove the physical barriers we have created and the social barriers that we have accepted. For ours will never be a truly prosperous nation until all within it prosper.”

President George Bush
upon signing the Americans with Disabilities Act
July 26, 1990

**Comment by HarmlessHarm** [comment]
Hi Saul,

Our answer: https://youtu.be/TxU8Fi8cgdE

Harm & Key
